name: Lighthouse CI

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  lighthouse:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for GitHub Pages to deploy
        run: sleep 30 # wait to ensure the site is deployed (adjust if needed)

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun --collect.url=https://daniel-tenzler.github.io
